/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InputZig {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `InputZig`'s JSON-Schema definition
 * via the `patternProperty` "^master$".
 *
 * This interface was referenced by `InputZig`'s JSON-Schema definition
 * via the `patternProperty` "^.*?\..*$".
 */
export interface ReleaseInfo {
  [k: string]: unknown;
}
